In [1]:
import numpy as np

In [2]:
mu, sigma = 10, 0.1 # mean and standard deviation
s = np.random.default_rng().normal(mu, sigma, size=(20000,20000))
s

array([[ 9.86237907,  9.94067379,  9.93498812, ..., 10.14328239,
        10.01285131,  9.87398329],
       [ 9.89517032, 10.06950884,  9.87703325, ..., 10.04609566,
        10.00243122, 10.16786035],
       [10.08483662,  9.81160933, 10.00646278, ..., 10.04395888,
         9.89070971, 10.01787876],
       ...,
       [10.04746142,  9.90682549, 10.04711766, ...,  9.84734449,
        10.04579584,  9.90967278],
       [10.09068016,  9.90651551,  9.76353195, ..., 10.05340209,
         9.87850331, 10.11336262],
       [10.00816126, 10.04785827,  9.86587009, ...,  9.93282457,
        10.16385222, 10.0543862 ]])

In [4]:
y= s 
%time z=y[::100,:].mean(axis=0)
z

Wall time: 6.54 ms


array([10.00263411,  9.99829717, 10.00902686, ...,  9.98776916,
       10.0126806 ,  9.99958192])

In [ ]:
# Start Dask Client for Dashboard
from dask.distributed import Client, progress
client = Client(processes=False, threads_per_worker=4,
                n_workers=1, memory_limit='6GB')
client

In [5]:
import dask.array as da
x = da.from_array(s, chunks=(1000,1000))

In [6]:
y= x 
z=y[::100,:].mean(axis=0)
z

dask.array<mean_agg-aggregate, shape=(20000,), dtype=float64, chunksize=(1000,), chunktype=numpy.ndarray>

In [7]:
z.compute()


array([10.00031544, 10.000978  ,  9.99626887, ..., 10.01192504,
       10.01224206,  9.99753872])

In [8]:
%time z.compute()

Wall time: 1.13 s


array([10.00031544, 10.000978  ,  9.99626887, ..., 10.01192504,
       10.01224206,  9.99753872])